### PR TITLE
repositories: add okh overlay

### PR DESCRIPTION
**Pull request by OlexiyKhokhlov**

### CODE REVIEW

**Comment by jsmolic** [comment]
Thanks for the PR! Can you please create a Bugzilla account with your e-mail address since we use Bugzilla to communicate any information about the repo

**Comment by OlexiyKhokhlov** [comment]
No problem, it's done

**Comment by jsmolic** [comment]
Thanks, we need to keep the list sorted by repo names, could you please change that?

**Review by jsmolic — APPROVED** [review]
Thanks, I'm going to squash and merge

**Pull request closed without merging**
