### PR TITLE
Request to add back to Gentoo tree after some issues.

### PR DESCRIPTION
**Pull request by archenroot**
Add archenroot

### CODE REVIEW

**Comment by archenroot** [comment]
I will, thx.

**Comment by archenroot** [comment]
I really wonder, why my output is different than yours... hm:
```
obile-server /var/lib/layman/archenroot # repoman full

RepoMan scours the neighborhood...
  DESCRIPTION.missing [fatal]   3
   dev-cpp/fbthrift/fbthrift-9999.ebuild
   dev-cpp/thpp/thpp-1.0.ebuild
   dev-cpp/thpp/thpp-9999.ebuild
  DESCRIPTION.toolong           15
   dev-cpp/fblualib/fblualib-9999.ebuild: DESCRIPTION is 146 characters (max 80)
   dev-db/apache-cassandra-bin/apache-cassandra-bin-3.0.13.ebuild: DESCRIPTION is 92 characters (max 80)
   dev-libs/active-object/active-object-9999.ebuild: DESCRIPTION is 116 characters (max 80)
   media-libs/avidemux-core/avidemux-core-2.6.18.ebuild: DESCRIPTION is 91 characters (max 80)
   media-libs/avidemux-plugins/avidemux-plugins-2.6.18.ebuild: DESCRIPTION is 94 characters (max 80)
   media-video/vsxu/vsxu-0.6.2.ebuild: DESCRIPTION is 86 characters (max 80)
   net-im/messenger-for-desktop-bin/messenger-for-desktop-bin-2.0.9.ebuild: DESCRIPTION is 109 characters (max 80)
   net-misc/activemq-bin/activemq-bin-5.13.1.ebuild: DESCRIPTION is 102 characters (max 80)
   net-misc/pooler-cpuminer/pooler-cpuminer-2.4.3.ebuild: DESCRIPTION is 100 characters (max 80)
   sci-libs/g3log/g3log-1.3.ebuild: DESCRIPTION is 116 characters (max 80)
   sci-libs/openmvg/openmvg-9999.ebuild: DESCRIPTION is 92 characters (max 80)
   sci-libs/torch-argcheck/torch-argcheck-9999.ebuild: DESCRIPTION is 97 characters (max 80)
   sci-libs/torch7/torch7-9999.ebuild: DESCRIPTION is 89 characters (max 80)
   sys-cluster/mesos/mesos-1.5.0.ebuild: DESCRIPTION is 104 characters (max 80)
   www-servers/oracle-glassfish-bin/oracle-glassfish-bin-4.1.ebuild: DESCRIPTION is 290 characters (max 80)

```
I have this version:
```
mobile-server /var/lib/layman/archenroot # eix repoman
[I] app-portage/repoman
     Available versions:  2.3.0-r1 2.3.3 ~2.3.4 2.3.6 **9999 {PYTHON_TARGETS="pypy python2_7 python3_4 python3_5 python3_6"}
     Installed versions:  2.3.6(11:55:36 01/19/18)(PYTHON_TARGETS="python2_7 python3_5 -python3_4 -python3_6")
     Homepage:            https://wiki.gentoo.org/wiki/Project:Portage
     Description:         Repoman is a Quality Assurance tool for Gentoo ebuilds

```

**Comment by mgorny** [comment]
Your Portage has probably already cached the results. Make sure to remove `metadata/*cache*` and `/var/cache/edb/dep`.

**Comment by mgorny** [comment]
Ping.

**Comment by archenroot** [comment]
@mgorny - finally I got things fixed, had to remove lot of ebuilds as it otherwise take me weeks/months to fix everything... :-)

**Comment by archenroot** [comment]
@mgorny - Hi Michal, can you please merge? It took me more than one year :-)

**Comment by mgorny** [comment]
Oh, sorry, i will do it now. I trust you've tested it with repoman this time.

**Comment by archenroot** [comment]
I have some new packages which doesn't work, but I think I didn't commit them yet...

**Comment by archenroot** [comment]
But I test with repoman in general continuously to prevent issues. Thx for help.

**Pull request closed without merging**
