### PR TITLE
repositories: Add natinst overlay

### PR DESCRIPTION
**Pull request by AndrewAmmerlaan**
Repository for VISA and National Instruments drivers ebuilds 

As discussed here: https://github.com/gentoo/sci/pull/993

### CODE REVIEW

**Review by mgorny — CHANGES_REQUESTED** [review]
Please fix indentation.

**Comment by AndrewAmmerlaan** [comment]
> Please fix indentation.

Oops, sorry about that, my editor did that automatically. Fixed it now.

**Comment by AndrewAmmerlaan** [comment]
Alright, *now* the indentation is correct :smile:

**Comment by mgorny** [comment]
Thanks!

**Comment by AndrewAmmerlaan** [comment]
Thank you!

**Pull request closed without merging**
