### PR TITLE
repositories: Add swirl

### PR DESCRIPTION
**Pull request by binex-dsk**
whitespace funny is because vim config did something, i can revert it if you like

### CODE REVIEW

**Comment by mgorny** [comment]
Could you split the whitespace changes into a separate commit? Also, why does the commit message say 'foo-overlay'?

**Comment by binex-dsk** [comment]
> Could you split the whitespace changes into a separate commit?

don't know if this is possible, but i'll try

> Also, why does the commit message say 'foo-overlay'?

Brain died and just typed exactly what I saw on the gentoo wiki without realizing to change the message

**Comment by binex-dsk** [comment]
@mgorny has been done

**Comment by mgorny** [comment]
Thanks. I'll strip the extra commits and sort.

**Pull request closed without merging**
