### PR TITLE
EAPI=4/5 ebuilds updated/removed from salfter overlay...please re-add

### PR DESCRIPTION
**Pull request by salfter**
WRT https://bugs.gentoo.org/792843...was a bit late catching this, but if the problem was what I think it is, it's been fixed.

### CODE REVIEW

**Comment by laumann** [comment]
Sure, could you amend the commit message and add a reference to the bug? Like this:

```
Bug: https://bugs.gentoo.org/792843
```

**Comment by laumann** [comment]
I think even better is to do just:
```
git revert 31746197a97eb70829afb75db3dcd19d37448ae4
```
and expand the commit message to explain the fixes done, and add the bug ref.

**Comment by laumann** [comment]
Sorry for not being clearer @salfter I meant for it to be just one commit, with a message like this:

```
Revert "repositories.xml: remove 'salfter' overlay"

This reverts commit 31746197a97eb70829afb75db3dcd19d37448ae4.

EAPI 4/5 ebuilds either updated or removed.

Bug: https://bugs.gentoo.org/792843
```
(you could also add a `Signed-off-by:` line after the `Bug:` line

**Comment by salfter** [comment]
It might be better at this point to close this request and open a new one.  I have a new branch waiting with just the one revert commit in it that will be uploaded shortly.  It seems to be the only way to keep unwanted cruft out of the repo.

**Comment by salfter** [comment]
New PR in https://github.com/gentoo/api-gentoo-org/pull/510 supersedes this one.

**Pull request closed without merging**
