### PR TITLE
repositories: Add status-check, bug:  #645056

### PR DESCRIPTION
**Pull request by powerhouseofthecell**
The bug number filed in Gentoo's Bugzilla for creating this package repository:  #645056

### CODE REVIEW

**Comment by mgorny** [comment]
CI sez you have a syntax error in XML:

```
files/overlays/repositories.xml:4327: parser error : Opening and ending tag mismatch: name line 4317 and repo
  </repo>
         ^
files/overlays/repositories.xml:5254: parser error : expected '>'
</repositories>
      ^
files/overlays/repositories.xml:5255: parser error : Premature end of data in tag repositories line 3
```

**Comment by powerhouseofthecell** [comment]
I found the missing bracket - sorry for not verifying earlier. But I can't seem to find this error. I couldn't access many specifics from the CI results. I'm sorry for any inconvenience.

**Comment by powerhouseofthecell** [comment]
Sorry for the mess I made at first, and for something very simple. My apologies.

**Comment by ChrisADR** [comment]
Hi @powerhouseofthecell, can you please squash your commits? thank you

**Pull request closed without merging**
