### PR TITLE
repositories: Add doublecmd-overlay

### PR DESCRIPTION
**Pull request by corvus1**
Ebuilds for:
app-misc/double-commander
dev-libs/libqt5pas
dev-lang/lazarus

### CODE REVIEW

**Comment by corvus1** [comment]
I don't know what's up with the unsorted list, I checked it 18 times already.

**Comment by corvus1** [comment]
Running bin/repositories-checker.py by hand returns no errors. I guess I still remember my ABCs, and the list is sorted correctly, must be something wrong with the CI.

**Comment by night-every** [comment]
> I don't know what's up with the unsorted list, I checked it 18 times already.

It is mentioned in repositories.xml. ‘When adding repositories, please keep this file ordered by repository name.’

**Comment by Flowdalic** [comment]
@arthurzam can you have a look at `repositories-checker.py`?

**Comment by arthurzam** [comment]
> @arthurzam can you have a look at `repositories-checker.py`?

The issue seems with the repo name 'Drauthius' which starts with upper case. @Flowdalic do you think we should make it case insensitive, aka call `.lower()` on `repo_name` in the `if` and `elif`:

https://github.com/gentoo/api-gentoo-org/blob/8c1cf65d58d280038e5a1e156cc039a2c3f34a53/bin/repositories-checker.py#L95-L101

**Comment by Flowdalic** [comment]
@corvus1: friendly reminder are you still interested in getting this merged?

**Comment by Flowdalic** [comment]
Closing due to inactivity. Feel free to reopen anytime.

**Pull request closed without merging**
