### PR TITLE
uid-gid.txt: new entries for ossec-hids

### PR DESCRIPTION
**Pull request by rseichter**
Add three new users and one shared new group for package net-analyzer/ossec-hids.

### CODE REVIEW

**Comment by rseichter** [comment]
@juippis The GID and UIDs are used in [this pull request](https://github.com/gentoo/gentoo/pull/14743).

**Comment by mschiff** [comment]
@rseichter Please could you modify your PR so the descriptions have a little more information about each user? (Instead of "User #2" ... )

**Comment by rseichter** [comment]
> Please could you modify your PR so the descriptions have a little more information about each user? (Instead of "User #2" ... )

Sorry, but I don't understand what you are asking. The file uid-gid.txt does not contain any information about the purpose of the requested users.

**Comment by rseichter** [comment]
If you are interested in what OSSEC uses the different accounts for, the [architecture description](https://ossec-documentation.readthedocs.io/en/latest/about/architecture.html#user-list) offers related information.

**Comment by rseichter** [comment]
@mschiff Just in case you were asking me for changes to [this PR](https://github.com/gentoo/gentoo/pull/14743), I have modified user descriptions to mention their respective purposes.

**Pull request closed without merging**
