### PR TITLE
repositories: add dj overlay

### PR DESCRIPTION
**Pull request by DJManas**
Hello,

Add my repository, not sure which process is ok, I had raised ticket on gentoo bugzilla according to documentation, but not sure if I should do pull request as well or not.

Thanks,
reagards,
Petr Sourek

### CODE REVIEW

**Comment by thesamesam** [comment]
> [dj] Conflicting repo_name, removing ("DJs_Repo" in repo_name, "dj" on list)

Could you fix `profiles/repo_name` in your repo, or change the name here? Thanks.

**Comment by DJManas** [comment]
I had changed dj to djs_overlay in the xml, later I had noticed, that the file should be in alphabetical order so I moved it after djc. And also changed the name to same name in profile/repo_name and push it into my git.

I hope its ok now, if anything, I will repair it, thanks for patience.

**Comment by thesamesam** [comment]
Thank you! Pushed now, fingers crossed that is it ;)

**Comment by DJManas** [comment]
You are welcome, thank you!

**Pull request closed without merging**
