### PR TITLE
mirrors: New additions

### PR DESCRIPTION
**Pull request by jpds**
Did another trawl of public mirror listings and verified that these had up-to-date stage3 tarballs.

### CODE REVIEW

**Comment by juippis** [comment]
Just to note: I've passed this on to our mirror team. Since to my understanding from the previous additions we did; even though these provide mirroring for now, apparently there's no contractual "guarantee" they can't walk away any moment. And that provides problematic times for our users. So some assurance from the mirroring institute should be provided if we are to list them.

**Comment by antarus12345** [comment]
Hello,

I'm interested in why we need to add more distfiles mirrors; as we operate distfiles.gentoo.org which is a CDN-backed global mirror network (as opposed to these individual community mirrors.) Is there some reason distfiles.g.o does not work for you (and thus we need to add more community mirrors?)

-A

**Comment by jpds** [comment]
@antarus12345 Curiously; I think I'm the polar-opposite of the CDN's target user, in that if I'm setting up a Gentoo box in Sweden - I want to use a mirror that I know is in Sweden (preferably one that has a peering connection to the AS number I'm at) and not a CDN - I never use distfiles.g.o on any of my gentoo machines. As a user like this, it's near-impossible to know where these community mirrors unless they're indexed somewhere.

I believe that the bouncer from the https://www.gentoo.org/downloads/ uses this distfiles mirror listing too.

**Comment by antarus12345** [comment]
> @antarus12345 Curiously; I think I'm the polar-opposite of the CDN's target user, in that if I'm setting up a Gentoo box in Sweden - I want to use a mirror that I know is in Sweden (preferably one that has a peering connection to the AS number I'm at) and not a CDN - I never use distfiles.g.o on any of my gentoo machines. As a user like this, it's near-impossible to know where these community mirrors unless they're indexed somewhere.

Is this a legal / governance requirement?

> 
> I believe that the bouncer from the https://www.gentoo.org/downloads/ uses this distfiles mirror listing too.

My problem is that we just don't have a great system to maintain these listings, so I'm not eager to expand them (because in 6 months they will be out of date, etc.)

What I think we want is a combination of these listings + filtering by mirrorstats.gentoo.org so we only list working mirrors; but the mechanization is not there yet. Would you be wiling to help contribute to that?

Then I think we can just merge whatever listings the community wants, and the automation will verify those listings and only list valid mirrors which is closer to the ideal.

-A

**Comment by jpds** [comment]
> Is this a legal / governance requirement?

It's more: if I know there's a good mirror nearby, I'll use it.

> What I think we want is a combination of these listings + filtering by mirrorstats.gentoo.org so we only list working mirrors; but the mechanization is not there yet. Would you be wiling to help contribute to that?

Sure, I'm on IRC with this nick.

**Comment by Flowdalic** [comment]
> My problem is that we just don't have a great system to maintain these listings, so I'm not eager to expand them (because in 6 months they will be out of date, etc.)

Does your concern still exists? I would volunteer to go through https://mirrorstats.gentoo.org/ and remove all mirrors that are all red and add mirrors from this PR that are still up to date (and then close this PR).

Would that be aggreeable?

**Comment by Flowdalic** [comment]
Thanks for your contribution. Merged all still up-to-date mirros. The only one that vanished was Easy Lee (https://github.com/gentoo/api-gentoo-org/pull/405/commits/77ba6cce6d48e850f6ae52a4f88135faf3c5b433).

**Pull request closed without merging**
