### PR TITLE
repositories: Add pzskc383-overlay

### PR DESCRIPTION
**Pull request by pzskc383**

### CODE REVIEW

**Comment by pzskc383** [comment]
Oh, I see, my cgit doesn't allow shallow clones. I'll fix that and retry afterwards.

**Comment by mgorny** [comment]
Ok. Please ping me if you need me to restart CI.

**Comment by pzskc383** [comment]
@mgorny fixed. You can try re-running CI now.

**Comment by mgorny** [comment]
The board is green now, and merging. Thanks!

**Pull request closed without merging**
