### PR TITLE
repositories: Add oddlama's personal overlay

### PR DESCRIPTION
**Pull request by oddlama**

### CODE REVIEW

**Comment by mgorny** [comment]
Could you please fix the CI failures? repo_name seems to be missing.

**Comment by oddlama** [comment]
Fixed. How do I re-trigger the CI?

**Comment by mgorny** [comment]
I've done it. For the future, you could just do a meaningless change (`git commit --amen --reset-author`) and repush.

**Comment by mgorny** [comment]
Thanks!

**Pull request closed without merging**
