### PR TITLE
Removed insecure source lines in repositories.xml where possible.

### PR DESCRIPTION
**Pull request by paul-jewell**
I have taken three different actions depending on the content of each entry:

1. If there were secure and insecure source entries, I removed the insecure entry
2. If there was only an insecure git:// entry pointing at github, I reformed it as git+ssh://git@...
3. If there was only one entry which was insecure but pointing at a different source host, I didn't change it. These are the repositories in this category: calculate, distros, haarp, interactive-fiction, k_f, lmiphay, mozilla, multilib-portage, xelnor

Hope this is OK!

### CODE REVIEW

**Comment by mgorny** [comment]
Thank you for your work.  However, I'm afraid this is not exactly right.

> 1. If there were secure and insecure source entries, I removed the insecure entry

I have no strong opinion on this.  Some people would argue that having unsecure fallback is better than being unable to checkout at all.  However, I think that at this point we can assume everyone will have HTTPS support in git, so it's fine.

> 2. If there was only an insecure git:// entry pointing at github, I reformed it as git+ssh://git@...

This means that people who don't have SSH key for github will not be able to checkout the repository.  Please use HTTPS instead.  Preferably, try to make all the entries use the same 'template', e.g. HTTPS first, then SSH.

**Comment by paul-jewell** [comment]
Thanks for your comments @mgorny - I do appreciate them :)
[reference insecure link removal]
> I have no strong opinion on this. 
Please accept my apologies - I misunderstood your comments when adding my overlay some months back - I thought you wanted to remove the insecure links where possible. I am happy to leave them in and use HTTPS, as opposed to git+ssh when creating secure links.
I am not sure how to make the order the same as the template - I will study the lxml library behaviour in more detail. 
If I understand your comment correctly, you would like:
1. Insecure links could be present, but should be fall back entries following secure links
2. The order of links should follow the templates: HTTPS, git+ssh then insecure
3. If there is only one insecure github entry, add an appropriate secure entry (HTTPS), retaining the insecure entry as fallback.
I look forward to your confirmation/adjustments!

**Comment by mgorny** [comment]
Actually, this wasn't exactly what I meant but if you put it like this, it makes sense.

Two things to be considered are:
a. A 'dumb' implementation (see eselect-repo) may use only the first URL, so the first URL should be something that is secure and works.
b. A 'less dumb' implementation (layman) will go from first to last.  In this context, SSH as second option is acceptable since if it fails, fallback will still happen.

**Comment by mgorny** [comment]
(NB I'm planning to add 'preferred protocol' option to eselect-repo at some point)

**Comment by paul-jewell** [comment]
I have the modified scripts on my PC at home (I'm in Brussels at the moment) - I'll get back to this during the week.

**Comment by mgorny** [comment]
Thanks a lot. I'll be looking forward to the results.

**Pull request closed without merging**
