### PR TITLE
repositories: update domain & email for swirl repository

### PR DESCRIPTION
**Pull request by binex-dsk**
got a new email and switched domains, changed to reflect this

### CODE REVIEW

**Comment by mgorny** [comment]
Can you update Bugzilla first? Or do you want me to update your Bugzilla account simultaneously?

**Comment by binex-dsk** [comment]
you can change it if you want, dont feel like changing it rn because busy

**Comment by binex-dsk** [comment]
hi i updated my bugzilla account @mgorny

**Comment by mgorny** [comment]
Thanks!

**Pull request closed without merging**
