### PR TITLE
bright: update repository URL

### PR DESCRIPTION
**Pull request by filalex77**

### CODE REVIEW

**Comment by mgorny** [comment]
Don't you want to update `<source/>` and `<feed/>` as well?

**Comment by filalex77** [comment]
@mgorny Thank you for noticing; I should do that.

**Comment by mgorny** [comment]
You need to ping us when force-pushing, GitHub doesn't mail about that.

**Comment by filalex77** [comment]
> You need to ping us when force-pushing, GitHub doesn't mail about that.

Thanks, didn't know that. Will keep in mind.

**Pull request closed without merging**
