### PR TITLE
Reinstate poly-c overlay

### PR DESCRIPTION
**Pull request by Polynomial-C**
Not sure why this was removed. I never said I will stop using Gentoo. In fact still I regularly update my overlay.

### CODE REVIEW

**Comment by Polynomial-C** [comment]
Not sure what my overlay has to do with this. I am using this overlay myself so if I'd do anything mailicous in it, I'd harm my own Gentoo installations. And again, it was removed based on a totally wrong assertion.

**Comment by jphook** [comment]
Folks, 

Why are you performing this kindergarden like behavior? 

If that overlay is still valid and gets updated, there is no reason for removing it. This is only affecting users.
I tried to look for alternatives until I realised this overlay is NOT closing.

If this is some personal grudge going on here, please do not pull the work at Gentoo into this.
A ban because of "inapropriate behaviour" is not a reason to remove a technical working overlay

my 2 cents

**Comment by SudoNova** [comment]
Hi, I think it's better to let interpersonal things remain interpersonal.
This overlay was always good and useful to me, I hope Gentoo devs revise their decision,
I also demand the respectable owner to make the git mirror of their overlay public again.

**Comment by juippis** [comment]
Anyone can add the overlay with:
eselect repository add poly-c rsync rsync://rsync.gentoofan.org/poly-c
eselect repository enable poly-c

**Comment by mgorny** [comment]
> Hi, I think it's better to let interpersonal things remain interpersonal. This overlay was always good and useful to me, I hope Gentoo devs revise their decision, I also demand the respectable owner to make the git mirror of their overlay public again.

It wouldn't be prudent for Gentoo (or to any other project) to redistribute something that slanders the project and its developers. We're happy to reintroduce it once the owner stops being total asshole, apologizes and retracts the total bullshit he published about us.

**Comment by Polynomial-C** [comment]
> > Hi, I think it's better to let interpersonal things remain interpersonal. This overlay was always good and useful to me, I hope Gentoo devs revise their decision, I also demand the respectable owner to make the git mirror of their overlay public again.
> 
> It wouldn't be prudent for Gentoo (or to any other project) to redistribute something that slanders the project and its developers. We're happy to reintroduce it once the owner stops being total asshole, apologizes and retracts the total bullshit he published about us.

Hey @mgorny! Long time no see :smile: 

Since you started to wash our dirty laundry in public, lets go, I am all in!

You accuse me of being an asshole? What about Comrel Bugs [[Bug 610596] mgorny routinely insults people](https://bugs.gentoo.org/610596), [[Bug 653192] take action against mgorny for suggesting violence....](https://bugs.gentoo.org/653192) and [[Bug 669228] Unprovoked attacks from mgorny (again)](https://bugs.gentoo.org/669228) (and many more that I can no longer look up for obvious reason) where you have been accused of being the same? You're being an asshole for the last decade but want me to stop being one? Dude, really?!?

Where do I 'slander' anyone? I left Gentoo because of Sam. He filed the comrel 'bugs' against me. Thats a fact! Calling me an ashole while having numerous own bugs against yourself... how shall we call that, hypocritical? I haven't posted even one false accusation, or one line which is not representing the truth. I am **documenting** the whole way you guys treating me from my point of view. 
I do not see any reason to apologize for that. If you don't like what you see, maybe you should ask yourself how you treat people.

@mgorny, if you don't want me to talk about what's really going on in Gentoo, I suggest to shut the fuck up and back off!

**Comment by mgorny** [comment]
I never claimed I'm perfect. I have made my share of mistakes, including attacking people who really didn't deserve it. However, it's not me running a hatefest against a totally innocent developer just because you can't stand that people who are good, nice and hard-working can achieve more in a few months than you did in your entire Gentoo time. If this were about me, I would just shrug and ignore it. But I don't want Sam to have trouble finding work because some asshole *insinuates* that he's some cause of conflicts in Gentoo, or to become as toxic as you are because you can't stand that he's still relatively innocent and not burned out, even though you did your best to destroy him.

Gentoo has had its share of toxic devs. I have had my share of conflicts with them, including yourself. However, over the last years I have attempted to fix our relations (even though you never really told me why you hated me so much) and treat you with respect. However, over the last few weeks you have proven to be probably the worst developer in the history of Gentoo. One who's not only very toxic but also who's willing to burn all the bridges and destroy everything just because he has unjustified hatred towards someone.

And let's make this straight: you weren't retired because of anyone *but yourself*. It's not others' fault for daring to live or try to work on Gentoo. It's yours for being petty, immature, hateful and completely unable to maintain even basic level of professionality. Which you just keep proving to be true.

What's really unfair here is that Gentoo maintains the level of professionality you don't. We don't go telling everyone why you were retired, how horrible person you are. We don't go all over the place trying to destroy your career. Perhaps we really should, considering how you're treating Sam. Perhaps we just should publish an official response to your slanderous post but I suppose even then you wouldn't realize how you make others feel.

That said, as you probably realize you've once again violated all the possible rules and ComRel's going to remove your post and your GitHub access. Still, I hope the time I've wasted on writing this may make you realize that what're you doing is just wrong.

**Comment by mgorny** [comment]
(comments deleted and user banned per ComRel request due to publishing confidential information and CoC violations)

**Comment by Watchdog-ID10T** [comment]
Hi Michal. 
Hurts if someone speaks the truth eh? 
You talk about a "long list of crimes", CoC Violations, publishing internal communication...

What about your crimes? 
Reading other members emails, copying them and giving them to others? Nudging others to create bugs against other members? Using Gentoo's ressources for your own stuff? 

You can delete this too. I am not mad. I know that criminals need to hide their tracks and try to keep stuff under the rug as long as they can. 
Just one small wink for you: You shouldn't run IRC clients on your mailservers. 

@Polynomial-C: If you need screenshots of this mess of a persons comments, tell me. 
@gentoo: You poor, poor, poor and blinded people. 
@mgorny: Prepare yourself ;-)

**Comment by mgorny** [comment]
> What about your crimes? Reading other members emails, copying them and giving them to others?

I'm sorry but I have never done anything like that. I don't understand why you keep pushing this accusation. I mean, I can't think of a single reason why I'd do something like that.

> Nudging others to create bugs against other members?
> Using Gentoo's ressources for your own stuff?

Could you be more specific?

> You can delete this too. I am not mad. I know that criminals need to hide their tracks and try to keep stuff under the rug as long as they can. Just one small wink for you: You shouldn't run IRC clients on your mailservers.

…but I don't?

**Comment by a17r** [comment]
@Watchdog-ID10T don't be stupid. "If you can't win the argument, change the conversation". That's what poly-c exercised here. He is the only one able to break out of the vicious circle he maneuvered himself into.

**Comment by Watchdog-ID10T** [comment]
> I'm sorry but I have never done anything like that. I don't understand why you keep pushing this accusation. I mean, I can't think of a single reason why I'd do something like that.
> 

I know. sounds bad if someone does this. Am I right? I don't know why you do this, but I know you did. - Or at least 'someone' from infra did. You are just my first guess since my logs show a polish IP address. 

> Could you be more specific?

To you? no. This, and everything else will be released to the public soon. To multiple eyes, and multiple people. 

> > You can delete this too. I am not mad. I know that criminals need to hide their tracks and try to keep stuff under the rug as long as they can. Just one small wink for you: You shouldn't run IRC clients on your mailservers.
> 
> …but I don't?

Someone does ;-)

**Comment by Watchdog-ID10T** [comment]
> @Watchdog-ID10T don't be stupid. "If you can't win the argument, change the conversation". That's what poly-c exercised here. He is the only one able to break out of the vicious circle he maneuvered himself into.

mgorny is offending people here, calling people names while he makes exactly the same BS he judges others for. He's lying, manipulating and overall a 'bad actor'.

Simplest proof for my words are this pull request.  "User stopped using gentoo" Is a blatant lie Michal used to justify his 'I am bigger than you' complex. Inconvient people are getting blocked, banned and removed. If he does not have anything against them, he talsk other people into accusing those he doesn't like. 

And he does this since years.

**Comment by mgorny** [comment]
> I know. sounds bad if someone does this. Am I right? I don't know why you do this, but I know you did. - Or at least 'someone' from infra did. You are just my first guess since my logs show a polish IP address.

You can accuse me of many things but really, are you accusing me of being an idiot? If I ever wanted to read your private mail (still, I didn't and I had no reason to), do you really think I'd be stupid enough to actually leave such an obvious trace? I mean, do you really think I would copy them to my private computer and, errr, wget some random `` tags or whatever?

If that's any help with your investigation, my ISP's IP addresses resolve to `*.icpnet.pl`.

**Comment by juippis** [comment]
To my knowledge the owner stated that they "don't want to have anything to do with Gentoo", which could be understood as literally **anything**. But ignoring that, having one's overlay listed here requires at least some degree of collaboration and communication between the owner and Gentoo, and knowing the owner, they're not capable of that. Nor would it be possible anymore either. So _removing_ the overlay would've been inevitable.

Regardless I'd like to point out my earlier comment in this thread about enabling the overlay using *eselect-repository*, which doesn't add any more steps compared to it being listed.

**Comment by mikhailkoliada** [comment]
@Watchdog-ID10T Lars, please relogin

**Pull request closed without merging**
