### PR TITLE
add sorrow overlay

### PR DESCRIPTION
**Pull request by eternal-sorrow**
I've set up the environment based on wayland compositor sway-1.0-beta1 and created some simple ebuilds for useful wayland software for that. I think, these ebuilds may be useful for someone.

### CODE REVIEW

**Comment by a17r** [comment]
1.0_beta1 is already in the process of being added to the tree.

**Comment by eternal-sorrow** [comment]
@a17r good to know.

**Comment by mgorny** [comment]
Please fix the CI issues and adjust the commit message to match other commits in the repo.

**Comment by eternal-sorrow** [comment]
@mgorny done

**Comment by mgorny** [comment]
Thanks.

**Pull request closed without merging**
