### PR TITLE
repositories: Add escpr2-overlay #662364

### PR DESCRIPTION
**Pull request by andreas-thalhammer**
https://bugs.gentoo.org/662364
Since I'm investing time in keeping the repo current, it would be nice if it was added to the official repositories list.
Thanks.

### CODE REVIEW

**Comment by mgorny** [comment]
The second line of your `repo_name` seems to be relying on undefined behavior.

**Comment by andreas-thalhammer** [comment]
> The second line of your `repo_name` seems to be relying on undefined behavior.

Fixed. In the documentation it somewhere stated that only the first line would be used, so that is the defined behaviour. I thought I'd use the second line to write the full repo's name. But I removed it now.

**Comment by mgorny** [comment]
> > The second line of your `repo_name` seems to be relying on undefined behavior.
> 
> Fixed. In the documentation it somewhere stated that only the first line would be used, so that is the defined behaviour. I thought I'd use the second line to write the full repo's name. But I removed it now.

See: https://dev.gentoo.org/~ulm/pms/head/pms.html

> repo_name
> Contains, on a single line, the name of this repository. [...]

I'm pretty sure that there are tools that rely on `cat profiles/repo_name` returning just that ;-).

**Comment by andreas-thalhammer** [comment]
Thanks!

**Pull request closed without merging**
