### PR TITLE
repositories: Add lanodanOverlay, #602496

### PR DESCRIPTION
**Pull request by lanodan**
Note: I added a french description, it’s optionnal, feel free to remove it

Bug report: https://bugs.gentoo.org/show_bug.cgi?id=602496

### CODE REVIEW

**Comment by lanodan** [comment]
I’m having issues with the toolchain on my server… for the first time in almost a year.
The issuer for https will probably be CACert so maybe it should probably be a fallback… but it’s currently an "old" StartSSL certificate which is in ca-certificates.
Also, is it possible to have mirrors ? (I have a mirror at gitlab.com for issues like this)

**Comment by mgorny** [comment]
> The issuer for https will probably be CACert so maybe it should probably be a fallback… but it’s currently an "old" StartSSL certificate which is in ca-certificates.

s/is/was/. Neither StartCom nor CACert are installed by default by current versions of ca-certificates. Both are deemed insecure.

> Also, is it possible to have mirrors ? (I have a mirror at gitlab.com for issues like this)

Yes. You can specify any URLs/mirrors, and they should be used in order. However, we require at least one working address (and preferably the first one) so we can actually sync it ;-). https is preferred since some users have outgoing git blocked.

**Comment by mgorny** [comment]
One more thing: we require that the overlay contact e-mail address is registered on bugs.gentoo.org, so we can easily file bugs against your overlay. Could you register an account or update it to match your Bugzilla account?

**Comment by lanodan** [comment]
Uh… bugzilla, git (at least the commit) and repositories.xml are using contact@hacktivis.me
And I put it know as my primary address for github.

**Comment by mgorny** [comment]
Oh, sorry, I failed at autocomplete. I'll merge it in a minute.

**Comment by mgorny** [comment]
Done. I've commented out your server to account for tools that do not support fallback addresses. Please let me know when it's fixed and working smoothly, I'll reenable them then (no need to PR).

**Comment by lanodan** [comment]
Ok, my git:// should be working now.

**Comment by lanodan** [comment]
Quite late on noting this one, https is using let’s encrypt instead of CACert.

**Comment by mgorny** [comment]
Readded.

**Pull request closed without merging**
